name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby: ['2.7.0']

    runs-on: '${{ matrix.os }}'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '${{ matrix.ruby }}'
    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.0
        bundle install
    - name: Run tests
      run: bundle exec rake spec
