name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.0
        bundle install
    - name: Run tests
      run: bundle exec rake spec
